
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb